baseurl = "/"  # End your URL with a `/` trailing slash.
title = "Educataional Patterns"
# copyright = "&copy; 2017 by Peter Baumgartner"
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img class="display-centered" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">This work</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://gedankensplitter.netlify.com" property="cc:attributionName" rel="cc:attributionURL">Peter Baumgartner</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.<br />Permissions beyond the scope of this license may be available at <a xmlns:cc="http://creativecommons.org/ns#" href="http://peter.baumgartner.name/kontakt" rel="cc:morePermissions">http://peter.baumgartner.name/kontakt</a>.'
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "↩"

# pb: copied from example Yihui Xie website
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

# Enable comments by entering your Disqus shortname
disqusShortname = "petzi"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-106233639-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# pb: Not sure, but I think it should not use blackfriday markdown/template?
[blackfriday]
   hrefTargetBlank = true


[params]
  name = "Peter Baumgartner"
  role = "Professor for Educational Technology"
  organization = "Danube University Krems"
  organization_url = "http://www.donau-uni.ac.at/"
  gravatar = true  # Get your avatar from Gravatar.com? (true/false)
  avatar = "" # "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "peter.baumgartner@donau-uni.ac.at"
  address = "Wing M, 2nd floor, Room 2.33, Danube University Krems, Dr.-Karl-Dorrek-Straße 30, 3500 Krems, Austria"
  office_hours = "email for appointment"
  phone = "+43 664/357 6661"
  skype = "baumgartner53"
  telegram = ""


  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"

date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["r", "yaml"]
  highlight_style = "github"
  highlight_version = "9.12.0" # or: 9.11.0 as in example?


  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ["hugo-academic-changes-mini.css"]
  custom_js  = []



  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:peter.baumgartner@donau-uni.ac.at"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/pbaumgartner"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.at/citations?user=mKCNn9kAAAAJ&hl=en"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/petzi53"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6


# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

[languages.de]
  languageCode = "de-de"

[[Languages.de.menu.main]]
  name = "Start"
  url = "#about_de"
  weight = 1

[[languages.de.menu.main]]
  name = "Kontakt"
  url = "#contact"
  weight = 6



############
# Languages
# Create a [languages.X] block for each language you want, where X is the language ID.

[Languages]
[Languages.en]
  title = "Thought Splinters"
  role = "Professor for Educational Technology"
  organization = "Danube University Krems"
  address = "Wing M, 2nd floor, Room 2.33, Danube University Krems, Dr.-Karl-Dorrek-Straße 30, 3500 Krems, Austria"
  office_hours = "email for appointment"

[Languages.de]
  title = "Gedankensplitter"
  role = "Professor für Bildungstechnologie"
  organization = "Donau-Universität Krems"
  address = "Büro: Trakt M, 2. Stock, Raum 2.33, Donau-Universität Krems, Dr.-Karl-Dorrek-Straße 30, 3500 Krems, Österreich"
  office_hours = "Terminvereinbarung über E-Mail"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

